### PR TITLE
Add SPDX-licenses

### PR DESCRIPTION
**Pull request by Kigaard**
Adding all the remaining SPDX with the exception of "or-later" in response to #99.
No existing licenses is removed but the SPDX-license list has been sorted alphabetically.

### CODE REVIEW

**Comment by matuskalas** [comment]
Thank you so much @Kigaard for diving into this! 🙏🏽

After my first look I'm somewhat confused about the licenses and which is where _etc._. Does anyone volunteer to dive into reviewing this thoroughly? 👾❓ @hmenager @veitveit @hansioan is anyone of you a license nerd or do you know one? If noone volunteers, I can do that, but it will have to be later.⏳ In such case, whoever, please ping me ⏰😊

**Comment by Kigaard** [comment]
I had some problems with branching/forking 😅, so it is only commit e0718b8, which is related to this PR. The first three comits are related to #206.

**Comment by Kigaard** [comment]
@matuskalas, I had some problems with branching/forking 😅 So it is only e0718b8, which is related to this PR. The first three comits are related to #206.

**Comment by hansioan** [comment]
Closing this as it contains data from a different PR and we also need to take step by step

**Pull request closed without merging**
